#!/bin/bash
FILE=$1

for i in $(seq 11 | tac); do
     DATE=`git log 0.${i} -n 1 | 
        grep Date |
        sed -e 's/Date:\s\+\(.\+\)\s-.*/\1/g'`;
     HEAD="\n0.${i} / ${DATE} \n==============================\n\n";
     printf "$HEAD" >> ${FILE};
     git log --pretty=format:" * %s" 0.${i}..0.$((i+1)) >> ${FILE};
     printf '\n' >> ${FILE};
done
